### ISSUE TITLE
child is null

### ISSUE THREAD

**Issue by kibotu** [timusus/RecyclerView-FastScroll#23]
happens when you return to the fragment having the recyclerview, there is a view element (like top shadow) overlapping on the recyclerview and it hasn't scrolled yet, i assume it tries to find the shadow within the recyclerview and fails

```
03-08 15:43:21.575  11532-11532/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.thecircle.debug, PID: 11532
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference
            at android.support.v7.widget.RecyclerView$LayoutManager.getDecoratedTop(RecyclerView.java:7654)
            at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.getCurScrollState(FastScrollRecyclerView.java:315)
            at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.onUpdateScrollbar(FastScrollRecyclerView.java:286)
            at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.draw(FastScrollRecyclerView.java:169)
            at android.view.View.updateDisplayListIfDirty(View.java:15180)
            at android.view.View.draw(View.java:15954)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
            at android.view.View.updateDisplayListIfDirty(View.java:15175)
            at android.view.View.draw(View.java:15954)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
            at android.view.View.draw(View.java:16187)
            at android.view.View.updateDisplayListIfDirty(View.java:15180)
            at android.view.View.draw(View.java:15954)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
            at android.view.View.updateDisplayListIfDirty(View.java:15175)
            at android.view.View.draw(View.java:15954)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
            at android.view.View.updateDisplayListIfDirty(View.java:15175)
            at android.view.View.draw(View.java:15954)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1369)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
            at android.view.View.updateDisplayListIfDirty(View.java:15175)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
            at android.view.View.updateDisplayListIfDirty(View.java:15140)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
            at android.view.View.updateDisplayListIfDirty(View.java:15140)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
            at android.view.View.updateDisplayListIfDirty(View.java:15140)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
            at android.view.View.updateDisplayListIfDirty(View.java:15140)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
            at android.view.View.updateDisplayListIfDirty(View.java:15140)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
            at android.view.View.updateDisplayListIfDirty(View.java:15140)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
            at android.view.Choreographer.doFrame(Choreographer.java:606)
            at android.view.Choreographer$FrameDisplayEventReceiver.ru
```

**Comment by ItsCalebJones** [comment]
Any news on this?

**Comment by kibotu** [comment]
well i've put up a pull request, you could just use my fork for now: https://github.com/Nammari/RecyclerView-FastScroll works with jitpack:

 compile 'com.github.kibotu:RecyclerView-FastScroll:1.0.8'

**Comment by timusus** [comment]
I'll have a look into it soon. I want to make sure the PR doesn't cause any side effects.

**Comment by kibotu** [comment]
actually for this issue the related part is merely that part, but gradle and sdk tools update is helpful, especially since recyclerview has had a lot of bugfixes:

https://github.com/Nammari/RecyclerView-FastScroll/pull/1/commits/e4c82cc15b92ed8dca685a0002014fc5d0ea07e3
