### ISSUE TITLE
Crash on API <= 15

### ISSUE THREAD

**Issue by neobie** [timusus/RecyclerView-FastScroll#40]
I capture multiple crashes on API lower then 15 from Crashlytics. A user reported that he cannot enter the Activity Screen totally.

Fatal Exception: java.lang.NullPointerException
       at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:513)
       at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:385)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:537)
       at android.animation.ValueAnimator.start(ValueAnimator.java:927)
       at android.animation.ValueAnimator.start(ValueAnimator.java:950)
       at android.animation.ObjectAnimator.start(ObjectAnimator.java:363)
       at com.simplecityapps.recyclerview_fastscroll.views.FastScroller$1.run(FastScroller.java:124)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4512)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by timusus** [comment]
I'm not sure what's going on there. 

Maybe the HideRunnable is being run after the RecyclerView has been detached from the Window, in certain situations. I don't have a device to test this on, and it may be only on specific devices.. Maybe you can provide more info from your Crashlytics data?

**Comment by timusus** [comment]
Not enough information provided to debug issue.
