### ISSUE TITLE
Render problem

### ISSUE THREAD

**Issue by MmtBkn** [timusus/RecyclerView-FastScroll#52]
Hi,

I just added library to project however I'm getting rendering problem. Any idea what can cause this?

```
java.lang.IllegalArgumentException: java.lang.ClassCastException@73980bc4
	at sun.reflect.GeneratedMethodAccessor1056.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at android.animation.PropertyValuesHolder_Delegate.callMethod(PropertyValuesHolder_Delegate.java:108)
	at android.animation.PropertyValuesHolder_Delegate.nCallIntMethod(PropertyValuesHolder_Delegate.java:140)
	at android.animation.PropertyValuesHolder.nCallIntMethod(PropertyValuesHolder.java)
	at android.animation.PropertyValuesHolder.access$200(PropertyValuesHolder.java:38)
	at android.animation.PropertyValuesHolder$IntPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1221)
	at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:989)
	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:612)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:578)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1001)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
	at com.simplecityapps.recyclerview_fastscroll.views.FastScroller.show(FastScroller.java:306)
	at com.simplecityapps.recyclerview_fastscroll.views.FastScroller$2.onScrolled(FastScroller.java:148)
	at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4618)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3679)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
	at android.support.v7.widget.RecyclerView.onLayout_Original(RecyclerView.java:3844)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.support.constraint.ConstraintLayout.onLayout_Original(ConstraintLayout.java:1197)
	at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout_Original(ActionBarOverlayLayout.java:437)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:17523)
	at android.view.ViewGroup.layout(ViewGroup.java:5612)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:345)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by timusus** [comment]
Fixed with 1f78c2e9956620c93a1f420703437087f13c76c3. I'll update the readme once v1.0.15 is live on Maven.
